# Generated by Django 4.0.2 on 2022-07-06 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='addJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=290)),
                ('description', models.TextField()),
                ('requirement', models.CharField(max_length=400)),
                ('salary', models.CharField(max_length=40)),
                ('experience', models.CharField(blank='Entry, Junior, Senior', max_length=200)),
                ('contact', models.EmailField(default='jobify@gmail.com', max_length=254)),
                ('location', models.CharField(default='Lagos,Nigeia', max_length=100)),
                ('job_type', models.CharField(max_length=90)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
