# Generated by Django 4.0.2 on 2022-07-06 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('id_user', models.IntegerField()),
                ('talent', models.CharField(max_length=100)),
                ('user_bio', models.TextField(blank=True)),
                ('years_of_experience', models.CharField(max_length=12)),
                ('portfolio_link', models.URLField(blank=True)),
                ('resume_upload', models.FileField(upload_to='users_resume')),
                ('skills', models.TextField(default='What are your skills?')),
                ('user_location', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
